
name: Build github pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2 # checkout gh-pages into a different folder
        with:
          ref: gh-pages
          path: www
          fetch-depth: 1
      - run: yarn install
      - run: yarn build-www
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "noreply@ticlo.com"
          git commit -m "Deploy Github Action"
        working-directory: ./www
      - run: git push
        working-directory: ./www
